services:
  mongodb-catalog-system:
    image: mongo:latest
    container_name: mongodb-catalog-system
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb-catalog-system:/data/db

volumes:
  mongodb-catalog-system:
